### PR TITLE
Use lossless quality for user banner and user avatar

### PR DESCRIPTION
**Pull request by truekas**
Noticed a little pixellation on my banner in the widget today, so I decided to make this PR
All this does is appends &quality=lossless to the URLs of the banner and avatar from the CDN.

### CODE REVIEW

**Comment by Vendicated** [comment]
have you verified that this indeed fixes the pixelation? it might also require increasing the resolution

**Comment by truekas** [comment]
Adding &quality=lossless to the CDN URL in a browser doesn't seem to affect the size of the image, but I'll compile and verify really quickly

**Comment by truekas** [comment]
yep, the resolution doesn't change.
image

**Comment by truekas** [comment]
this PR has been open for a while now, will it be merged?

**Comment by Vendicated** [comment]
i know that it doesn't change the resolution. I was asking whether adding lossless fixes your issue of pixelation

**Comment by truekas** [comment]
Yes, it fixes the issue

**Comment by KannaDev** [comment]
> i know that it doesn't change the resolution. I was asking whether adding lossless fixes your issue of pixelation

@Vendicated It seems that it does improve pixelation, and its primarily noticeable on banners that have more detail.

**Comment by Vendicated** [comment]
thanks!

**Pull request merged**
